### ISSUE TITLE
Could you update this for 2019. It looks useful

### ISSUE THREAD

**Issue by JosephDunivan** [martinnormark/ShareByMail#1]

**Comment by martinnormark** [comment]
Should work the same, start a new project and add the things from here on top.

**Comment by JosephDunivan** [comment]
It actually came up with tons of errors when I copy and pasted everything into a new project. Really didn’t work at all because there were too many deprecated methods.

**Comment by ldenoue** [comment]
On iOS 13 it looks like it always shows up as a popover, not reaching the full screen. Any ideas?
